name: Build And Push Book Library Backend Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'not_empty'
    - name: Add Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Login To Server
      run: ssh -t root@5.101.50.241 exit 
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag msberyanov/book-library-backend
    - name: Login To Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker Image
      run: docker push msberyanov/book-library-backend
    - name: Pull Image On Server
      run: ssh -t root@5.101.50.241 "docker run -p 8080:8080 msberyanov/book-library-backend; exit"
