name: Build And Push Book Library Backend Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  book-library-backend-build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'not_empty'
    - name: Add known hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Login to server
      run: ssh -T root@${{ secrets.SSH_HOST }} exit 
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag msberyanov/book-library-backend
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image
      run: docker push msberyanov/book-library-backend
    - name: Pull image on server
      run: >
        ssh -T root@${{ secrets.SSH_HOST }} "docker ps -aq | xargs docker stop | xargs docker rm; 
        docker pull msberyanov/book-library-backend;
        docker run -d -p 8080:8080 msberyanov/book-library-backend;
        exit"
